apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          hostPort: 80  # Optional: Expose port 80 on the host (requires elevated privileges)
        volumeMounts:
        - name: www  # Mount a volume for serving content
      volumes:
      - name: www
        emptyDir: {}  # Empty directory volume to store your web content
