apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m  # Set CPU request (e.g., 100 millicores)
        memory: 128Mi  # Set memory request (e.g., 128 Megabytes)
      limits:
        cpu: 200m  # Set CPU limit (e.g., maximum 200 millicores)
        memory: 256Mi  # Se
